### ISSUE TITLE
ubuntu 20.04 安装opencv 3.4.4.19 失败

### ISSUE THREAD

**Issue by ghost** [alisen39/TrWebOCR#106]
![Screenshot_20220518-095508_ConnectBot](https://user-images.githubusercontent.com/102346830/168941347-6182e3a0-7dee-4d07-82f5-8d162eecbef5.png)

**Comment by ghost** [comment]
安装最新版的opencv和其他依赖后运行该项目报错

**Comment by ghost** [comment]
![Screenshot_20220518-103048_ConnectBot](https://user-images.githubusercontent.com/102346830/168945434-0efb9831-cca9-4428-8848-3411a6de6e71.png)

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "backend/main.py", line 55, in <mo
dule>
    app = make_app()
  File "backend/main.py", line 31, in mak
e_app
    from backend.webInterface import tr_r
un
  File "/root/TrWebOCR/backend/webInterfa
ce/tr_run.py", line 7, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-pac
kages/cv2/__init__.py", line 8, in <modul
e>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shar
ed object file: No such file or directory

**Comment by ghost** [comment]
os verison
ubuntu 20.04
python 3.8
opencv(pip install opencv-python 直接安装)

**Comment by monkey6** [comment]
python版本不对，安装3.7的python版本就可以了
