### ISSUE TITLE
树莓派运行报错，请问这个怎样解决？？ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by huangweian** [alisen39/TrWebOCR#42]
root@raspberrypi:~/TrWebOCR-master# python backend/main.py 
Traceback (most recent call last):
  File "backend/main.py", line 10, in <module>
    from backend.webInterface import tr_run
  File "/root/TrWebOCR-master/backend/webInterface/tr_run.py", line 8, in <module>
    import tr
  File "/root/TrWebOCR-master/backend/tr/__init__.py", line 2, in <module>
    from .tr import *
  File "/root/TrWebOCR-master/backend/tr/tr.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by alisen39** [comment]
这个是python里面没有安装opencv的报错，安装一下应该就可以了~

**Comment by shuaidie** [comment]
pip install python-opencv
