### ISSUE TITLE
Win10下面不能运行，是因为缺失 libtr.dll吗？

### ISSUE THREAD

**Issue by RockChang** [alisen39/TrWebOCR#6]
Traceback (most recent call last):
  File "backend/main.py", line 10, in <module>
    from backend.webInterface import tr_run
  File "c:\Projects\TrWebOCR\TrWebOCR-master\backend\webInterface\tr_run.py", line 8, in <module>
    import tr
  File "c:\Projects\TrWebOCR\TrWebOCR-master\backend\tr\__init__.py", line 2, in <module>
    from .tr import *
  File "c:\Projects\TrWebOCR\TrWebOCR-master\backend\tr\tr.py", line 22, in <module>
    _libc = ctypes.cdll.LoadLibrary(os.path.join(_BASEDIR, 'libtr.dll'))
  File "C:\ProgramData\Miniconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Miniconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by alisen39** [comment]
因为libtorch在windows下有一些bug，所以没有提供dll出来  
可以参考这个issuse:  
https://github.com/myhub/tr/issues/31#issuecomment-579139459
