### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by ChoGathK** [alisen39/TrWebOCR#9]
Traceback (most recent call last):
  File "backend/main.py", line 11, in <module>
    from backend.webInterface import tr_run
  File "/Users/fizz/the-world/TrWebOCR/backend/webInterface/tr_run.py", line 8, in <module>
    import tr
  File "/Users/fizz/the-world/TrWebOCR/backend/tr/__init__.py", line 2, in <module>
    from .tr import *
  File "/Users/fizz/the-world/TrWebOCR/backend/tr/tr.py", line 24, in <module>
    _libc = ctypes.cdll.LoadLibrary(os.path.join(_BASEDIR, 'libtr.so'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/fizz/the-world/TrWebOCR/backend/tr/libtr.so, 6): no suitable image found.  Did find:
        /Users/fizz/the-world/TrWebOCR/backend/tr/libtr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
        /Users/fizz/the-world/TrWebOCR/backend/tr/libtr.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

**Comment by ChoGathK** [comment]
Python 3.7.6

Package       Version 
------------- --------
libtorch      1.2.0.1 
numpy         1.14.6  
OpenCC        1.1.1   
opencv-python 3.4.4.19
Pillow        5.4.0   
pip           20.0.2  
python-lzf    0.2.4   
rdbtools      0.1.14  
redis         3.4.1   
setuptools    41.2.0  
tornado       6.0.4   
tr            1.0.0.3

**Comment by boomsi** [comment]
请问怎么解决的
